In [2]:
import pandas as pd

### Знакомство в DataFrame

In [13]:
# при объявлении df можно специфицировать колонки и индексы:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns = ['A', 'B', 'C'], index=['x','y','z'])

In [12]:
df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [7]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [10]:
# как получить список индексов:
df.index.tolist()

[0, 1, 2]

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

int64 == 64 Bits == 8 Bytes

In [15]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [20]:
df['A'].unique() # вернуть уникальные значения столбца

array([1, 4, 7])

In [22]:
df.shape

(3, 3)

In [24]:
df.size # сколько ячеек

9

### Загрузка данных в Dataframe

In [55]:
from pathlib import Path
import os

In [58]:
os.getcwd()

'd:\\DevProjects\\pandas_edu\\Andrey_nb'

In [63]:
#запишем путь - который будет работать:
file_path_coffee = Path('../complete-pandas-tutorial/warmup-data/coffee.csv')

In [64]:
file_path_coffee.exists()

True

In [107]:
coffee = pd.read_csv('../complete-pandas-tutorial/warmup-data/coffee.csv')

In [67]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [79]:
#формат который горозадо легче и быстрее загружается:
results = pd.read_parquet('../complete-pandas-tutorial/data/results.parquet')

In [74]:
results.shape

(308408, 11)

In [78]:
olympics_data = pd.read_excel('../complete-pandas-tutorial/data/olympics-data.xlsx')

In [80]:
bios = pd.read_csv('../complete-pandas-tutorial/data/bios.csv')

### Получение данных с помощью Pandas

In [82]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [87]:
coffee.sample(5, random_state = 1)

         Day Coffee Type  Units Sold
3    Tuesday       Latte          20
7   Thursday       Latte          30
6   Thursday    Espresso          40
2    Tuesday    Espresso          30
10  Saturday    Espresso          45

#### Применение loc и iloc

In [90]:
# то, как работает loc:
#coffee.loc[Rows, Columns]

coffee.loc[0] #возвращается серия в виде первой строки

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [92]:
coffee.loc[[0,1,2]] # вернем первые три строки

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [94]:
coffee.loc[5:8, ["Day", 'Units Sold']] # выберем только тек колонки которые нужны - к нашим строкам

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

In [96]:
coffee.iloc[:, [0,2]] # все строки и два столбца

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [100]:
# можно пользоваться заменами индексов на что-то значащие:
coffee.index = coffee["Day"]

In [108]:
coffee.loc[1:3, "Units Sold"] = 10

In [109]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          10
3     Tuesday       Latte          10
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [112]:
coffee.at[0, "Units Sold"] # получаем значение на пересечении - для единичного значения

np.int64(25)

In [117]:
coffee.sort_values(["Units Sold", 'Coffee Type'], ascending = [0,1]) 
# можно задать разные направления для разных столбцов

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

#### Как происходит итерация:

In [121]:
# переборы - не особо оптимизирован под циклы - но для анализа - ок:
for index, row in coffee.iterrows():
    print(index)
    print(row['Units Sold'])

0
25
1
10
2
10
3
10
4
35
5
25
6
40
7
30
8
45
9
35
10
45
11
35
12
45
13
35

### Фильтрация данных:

In [122]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [126]:
# отфильтровали строки и взяли нужные нам столбцы:
bios.loc[bios['height_cm']>215, ['name', 'height_cm']].sort_values('height_cm')

                         name  height_cm
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6722         Shaquille O'Neal      216.0
6409         Sergey Kovalenko      216.0
6937           David Robinson      216.0
118663         Timofey Mozgov      216.0
123850         Tyson Chandler      216.0
121694            Salah Mejri      216.0
112332    Andreas Glyniadakis      216.0
138671          Ondřej Balvín      216.0
52608         Aleksey Kazakov      217.0
112312           Stanko Barać      217.0
5583     Paulinho Villas Boas      217.0
7074           Paulo da Silva      217.0
130461                Zhou Qi      217.0
7281         Stojko Vranković      217.0
130460               Li Muhao      218.0
112337          Hamed Haddadi      218.0
82100           Frédéric Weis      218.0
7376      Eurelijus Žukauskas      218.0
5796            Andy Campbell      218.0
139365         Moustapha Fall      218.0
6420            Jānis Krūmiņš      218.0
5716                 Uwe Blab      218.0
118676        Dmitry Musersky      219.0
107408       Peter John Ramos      219.0
6504              Luc Longley      220.0
5089       Viktor Pankrashkin      220.0
7188       Vladimir Tkachenko      220.0
120266           Zhang Zhaoxu      221.0
5673           Gunther Behnke      221.0
89075          Roberto Dueñas      221.0
5781           Tommy Burleson      223.0
6978          Arvydas Sabonis      223.0
89070                Yao Ming      226.0

In [ ]:
#можно фильтровать проще:
bios[bios['height_cm']>215][['name', 'height_cm']]

In [132]:
#Несколько условий:
bios[(bios['height_cm']>215) & (bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [ ]:
# поиск по содержанию: чувствительно к регистру
bios[bios['name'].str.contains('Keith|patrick', case=False)] # можно использовать синтаксис регулярных вражений, его можно отключить - чтобы искать точно совпадение

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [139]:
#можно записать запрос без повторения наименования df:
bios.query('born_country == "USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN