In [ ]:
import pandas as pd

### Знакомство в DataFrame

In [ ]:
# при объявлении df можно специфицировать колонки и индексы:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns = ['A', 'B', 'C'], index=['x','y','z'])

In [ ]:
df.head()

In [ ]:
df.columns

In [ ]:
# как получить список индексов:
df.index.tolist()

In [ ]:
df.info()

int64 == 64 Bits == 8 Bytes

In [ ]:
df.describe()

In [ ]:
df['A'].unique() # вернуть уникальные значения столбца

In [ ]:
df.shape

In [ ]:
df.size # сколько ячеек

### Загрузка данных в Dataframe

In [ ]:
from pathlib import Path
import os

In [ ]:
os.getcwd()

In [ ]:
#запишем путь - который будет работать:
file_path_coffee = Path('../complete-pandas-tutorial/warmup-data/coffee.csv')

In [ ]:
file_path_coffee.exists()

In [ ]:
coffee = pd.read_csv('../complete-pandas-tutorial/warmup-data/coffee.csv')

In [ ]:
coffee.head()

In [ ]:
#формат который горозадо легче и быстрее загружается:
results = pd.read_parquet('../complete-pandas-tutorial/data/results.parquet')

In [ ]:
results.shape

In [ ]:
olympics_data = pd.read_excel('../complete-pandas-tutorial/data/olympics-data.xlsx')

In [ ]:
bios = pd.read_csv('../complete-pandas-tutorial/data/bios.csv')

### Получение данных с помощью Pandas

In [ ]:
display(coffee)

In [ ]:
coffee.sample(5, random_state = 1)

#### Применение loc и iloc

In [ ]:
# то, как работает loc:
#coffee.loc[Rows, Columns]

coffee.loc[0] #возвращается серия в виде первой строки

In [ ]:
coffee.loc[[0,1,2]] # вернем первые три строки

In [ ]:
coffee.loc[5:8, ["Day", 'Units Sold']] # выберем только тек колонки которые нужны - к нашим строкам

In [ ]:
coffee.iloc[:, [0,2]] # все строки и два столбца

In [ ]:
# можно пользоваться заменами индексов на что-то значащие:
coffee.index = coffee["Day"]

In [ ]:
coffee.loc[1:3, "Units Sold"] = 10

In [ ]:
coffee

In [ ]:
coffee.at[0, "Units Sold"] # получаем значение на пересечении - для единичного значения

In [ ]:
coffee.sort_values(["Units Sold", 'Coffee Type'], ascending = [0,1]) 
# можно задать разные направления для разных столбцов

#### Как происходит итерация:

In [ ]:
# переборы - не особо оптимизирован под циклы - но для анализа - ок:
for index, row in coffee.iterrows():
    print(index)
    print(row['Units Sold'])

### Фильтрация данных:

In [ ]:
bios.info()

In [ ]:
# отфильтровали строки и взяли нужные нам столбцы:
bios.loc[bios['height_cm']>215, ['name', 'height_cm']].sort_values('height_cm')

In [ ]:
#можно фильтровать проще:
bios[bios['height_cm']>215][['name', 'height_cm']]

In [ ]:
#Несколько условий:
bios[(bios['height_cm']>215) & (bios['born_country']=='USA')]

In [ ]:
# поиск по содержанию: чувствительно к регистру
bios[bios['name'].str.contains('Keith|patrick', case=False)] # можно использовать синтаксис регулярных вражений, его можно отключить - чтобы искать точно совпадение

In [ ]:
#можно записать запрос без повторения наименования df:
bios.query('born_country == "USA"')

### Добавление / Удаление колонок

In [41]:
#Как добавить колонку со значением:
coffee['price'] = 4.99

In [34]:
coffee.head()

                 Day Coffee Type  Units Sold  price
Day
Monday        Monday    Espresso          25   4.99
Monday        Monday       Latte          15   4.99
Tuesday      Tuesday    Espresso          30   4.99
Tuesday      Tuesday       Latte          20   4.99
Wednesday  Wednesday    Espresso          35   4.99

In [36]:
import numpy as np

In [38]:
#Теперь добавим колонку с простым условием:
coffee['new_price'] = np.where(coffee['Coffee Type']=='Espresso', 3.99, 5.99)
coffee.head()

                 Day Coffee Type  Units Sold  price  new_price
Day
Monday        Monday    Espresso          25   4.99       3.99
Monday        Monday       Latte          15   4.99       5.99
Tuesday      Tuesday    Espresso          30   4.99       3.99
Tuesday      Tuesday       Latte          20   4.99       5.99
Wednesday  Wednesday    Espresso          35   4.99       3.99

In [42]:
#удалим колонку:
coffee.drop(columns=['price'], inplace=True)

In [43]:
coffee.head()

                 Day Coffee Type  Units Sold  new_price
Day
Monday        Monday    Espresso          25       3.99
Monday        Monday       Latte          15       5.99
Tuesday      Tuesday    Espresso          30       3.99
Tuesday      Tuesday       Latte          20       5.99
Wednesday  Wednesday    Espresso          35       3.99

In [44]:
# важный момент - чтобы создать копию df - нужно использовать метод copy - иначе будет ссылка на оригинал и изменения будут в обоих df:
coffee_copy = coffee.copy()

In [45]:
coffee['revenue']= coffee['Units Sold'] * coffee['new_price']

In [47]:
coffee.head()

                 Day Coffee Type  Units Sold  new_price  revenue
Day
Monday        Monday    Espresso          25       3.99    99.75
Monday        Monday       Latte          15       5.99    89.85
Tuesday      Tuesday    Espresso          30       3.99   119.70
Tuesday      Tuesday       Latte          20       5.99   119.80
Wednesday  Wednesday    Espresso          35       3.99   139.65

In [50]:
#переименуем колонку:
coffee.rename(columns={'new_price':'price'}, inplace=True)

In [51]:
coffee.head()

                 Day Coffee Type  Units Sold  price  revenue
Day
Monday        Monday    Espresso          25   3.99    99.75
Monday        Monday       Latte          15   5.99    89.85
Tuesday      Tuesday    Espresso          30   3.99   119.70
Tuesday      Tuesday       Latte          20   5.99   119.80
Wednesday  Wednesday    Espresso          35   3.99   139.65

In [52]:
bios_new = bios.copy()

In [53]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [54]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [55]:
#поработаем с объектами даты и времени
bios_new['born_date']= pd.to_datetime(bios_new['born_date'])

In [56]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  datetime64[us]
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
 10  first_name    145500 non-null  object
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(6)
memory usage: 18.2+ MB

In [62]:
bios_new['Year of Birth'] = bios_new['born_date'].dt.year

In [63]:
bios_new[['name', 'Year of Birth']].head()

                    name  Year of Birth
0  Jean-François Blanchy         1886.0
1         Arnaud Boetsch         1969.0
2           Jean Borotra         1898.0
3        Jacques Brugnon         1895.0
4           Albert Canet         1878.0

In [68]:
#простые функции с lyambda:
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x: 'Tall' if x > 190 else 'Average' if x > 170 else 'Short')

In [70]:
bios_new[['name', 'height_cm', 'height_category']].head(10)

                    name  height_cm height_category
0  Jean-François Blanchy        NaN           Short
1         Arnaud Boetsch      183.0         Average
2           Jean Borotra      183.0         Average
3        Jacques Brugnon      168.0           Short
4           Albert Canet        NaN           Short
5      Nicolas Chatelain      181.0         Average
6          Patrick Chila      180.0         Average
7           Henri Cochet        NaN           Short
8          Marcel Cousin        NaN           Short
9     Guy de la Chapelle        NaN           Short

In [74]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   athlete_id       145500 non-null  int64
 1   name             145500 non-null  str
 2   born_date        143693 non-null  datetime64[us]
 3   born_city        110908 non-null  str
 4   born_region      110908 non-null  str
 5   born_country     110908 non-null  str
 6   NOC              145499 non-null  str
 7   height_cm        106651 non-null  float64
 8   weight_kg        102070 non-null  float64
 9   died_date        33940 non-null   str
 10  first_name       145500 non-null  object
 11  Year of Birth    143693 non-null  float64
 12  height_category  145500 non-null  str
dtypes: datetime64[us](1), float64(3), int64(1), object(1), str(7)
memory usage: 21.3+ MB

In [83]:
def categorize_athlete(row):
    if pd.isna(row['height_cm']) or pd.isna(row['weight_kg']):
        return 'Unknown'    
    elif row['height_cm'] < 170 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] >= 170 and row['height_cm'] < 190 and row['weight_kg'] >= 70 and row['weight_kg'] < 80:
        return 'Middleweight'
    else:
        return 'Heavyweight'

In [84]:
bios_new['Category'] = bios_new.apply(categorize_athlete, axis=1)

In [85]:
bios_new[['name', 'height_cm',  'weight_kg', 'Category']].head()

                    name  height_cm  weight_kg      Category
0  Jean-François Blanchy        NaN        NaN       Unknown
1         Arnaud Boetsch      183.0       76.0  Middleweight
2           Jean Borotra      183.0       76.0  Middleweight
3        Jacques Brugnon      168.0       64.0   Lightweight
4           Albert Canet        NaN        NaN       Unknown

### Merging and Concatinating

In [88]:
nocs = pd.read_csv('../complete-pandas-tutorial/data/noc_regions.csv')

In [90]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [92]:
bios2 = pd.merge(bios_new, nocs, left_on='born_country', right_on='NOC', how='left')

In [95]:
bios2.rename(columns={'region':'born_country_full'}, inplace=True)

In [96]:
bios2[['name', 'born_country', 'born_country_full']].head(15)

                       name born_country born_country_full
0     Jean-François Blanchy          FRA            France
1            Arnaud Boetsch          FRA            France
2              Jean Borotra          FRA            France
3           Jacques Brugnon          FRA            France
4              Albert Canet          GBR                UK
5         Nicolas Chatelain          FRA            France
6             Patrick Chila          FRA            France
7              Henri Cochet          FRA            France
8             Marcel Cousin          FRA            France
9        Guy de la Chapelle          FRA            France
10  Élie, Comte de Lastours          FRA            France
11              Max Decugis          FRA            France
12                J. Defert          NaN               NaN
13           Étienne Durand          NaN               NaN
14              Damien Éloi          FRA            France