In [1]:
import pandas as pd

### Знакомство в DataFrame

In [2]:
# при объявлении df можно специфицировать колонки и индексы:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns = ['A', 'B', 'C'], index=['x','y','z'])

In [3]:
df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [4]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [5]:
# как получить список индексов:
df.index.tolist()

['x', 'y', 'z']

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

int64 == 64 Bits == 8 Bytes

In [7]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [8]:
df['A'].unique() # вернуть уникальные значения столбца

array([1, 4, 7])

In [9]:
df.shape

(3, 3)

In [10]:
df.size # сколько ячеек

9

### Загрузка данных в Dataframe

In [11]:
from pathlib import Path
import os

In [12]:
os.getcwd()

'c:\\Users\\user\\_Devs\\pandas\\pandas_edu\\Andrey_nb'

In [13]:
#запишем путь - который будет работать:
file_path_coffee = Path('../complete-pandas-tutorial/warmup-data/coffee.csv')

In [14]:
file_path_coffee.exists()

True

In [15]:
coffee = pd.read_csv('../complete-pandas-tutorial/warmup-data/coffee.csv')

In [16]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [17]:
#формат который горозадо легче и быстрее загружается:
results = pd.read_parquet('../complete-pandas-tutorial/data/results.parquet')

In [18]:
results.shape

(308408, 11)

In [19]:
olympics_data = pd.read_excel('../complete-pandas-tutorial/data/olympics-data.xlsx')

In [20]:
bios = pd.read_csv('../complete-pandas-tutorial/data/bios.csv')

### Получение данных с помощью Pandas

In [21]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [22]:
coffee.sample(5, random_state = 1)

         Day Coffee Type  Units Sold
3    Tuesday       Latte          20
7   Thursday       Latte          30
6   Thursday    Espresso          40
2    Tuesday    Espresso          30
10  Saturday    Espresso          45

#### Применение loc и iloc

In [23]:
# то, как работает loc:
#coffee.loc[Rows, Columns]

coffee.loc[0] #возвращается серия в виде первой строки

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [24]:
coffee.loc[[0,1,2]] # вернем первые три строки

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [25]:
coffee.loc[5:8, ["Day", 'Units Sold']] # выберем только тек колонки которые нужны - к нашим строкам

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

In [26]:
coffee.iloc[:, [0,2]] # все строки и два столбца

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [27]:
# можно пользоваться заменами индексов на что-то значащие:
#coffee.index = coffee["Day"]

In [28]:
coffee.loc[1:3, "Units Sold"] = 10

In [29]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          10
3     Tuesday       Latte          10
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [30]:
coffee.at[0, "Units Sold"] # получаем значение на пересечении - для единичного значения

np.int64(25)

In [31]:
coffee.sort_values(["Units Sold", 'Coffee Type'], ascending = [0,1]) 
# можно задать разные направления для разных столбцов

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

#### Как происходит итерация:

In [32]:
# переборы - не особо оптимизирован под циклы - но для анализа - ок:
for index, row in coffee.iterrows():
    print(index)
    print(row['Units Sold'])

0
25
1
10
2
10
3
10
4
35
5
25
6
40
7
30
8
45
9
35
10
45
11
35
12
45
13
35

### Фильтрация данных:

In [33]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [34]:
# отфильтровали строки и взяли нужные нам столбцы:
bios.loc[bios['height_cm']>215, ['name', 'height_cm']].sort_values('height_cm')

                         name  height_cm
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6722         Shaquille O'Neal      216.0
6409         Sergey Kovalenko      216.0
6937           David Robinson      216.0
118663         Timofey Mozgov      216.0
123850         Tyson Chandler      216.0
121694            Salah Mejri      216.0
112332    Andreas Glyniadakis      216.0
138671          Ondřej Balvín      216.0
52608         Aleksey Kazakov      217.0
112312           Stanko Barać      217.0
5583     Paulinho Villas Boas      217.0
7074           Paulo da Silva      217.0
130461                Zhou Qi      217.0
7281         Stojko Vranković      217.0
130460               Li Muhao      218.0
112337          Hamed Haddadi      218.0
82100           Frédéric Weis      218.0
7376      Eurelijus Žukauskas      218.0
5796            Andy Campbell      218.0
139365         Moustapha Fall      218.0
6420            Jānis Krūmiņš      218.0
5716                 Uwe Blab      218.0
118676        Dmitry Musersky      219.0
107408       Peter John Ramos      219.0
6504              Luc Longley      220.0
5089       Viktor Pankrashkin      220.0
7188       Vladimir Tkachenko      220.0
120266           Zhang Zhaoxu      221.0
5673           Gunther Behnke      221.0
89075          Roberto Dueñas      221.0
5781           Tommy Burleson      223.0
6978          Arvydas Sabonis      223.0
89070                Yao Ming      226.0

In [35]:
#можно фильтровать проще:
bios[bios['height_cm']>215][['name', 'height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [36]:
#Несколько условий:
bios[(bios['height_cm']>215) & (bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [37]:
# поиск по содержанию: чувствительно к регистру
bios[bios['name'].str.contains('Keith|patrick', case=False)] # можно использовать синтаксис регулярных вражений, его можно отключить - чтобы искать точно совпадение

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [38]:
#можно записать запрос без повторения наименования df:
bios.query('born_country == "USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

### Добавление / Удаление колонок

In [39]:
#Как добавить колонку со значением:
coffee['price'] = 4.99

In [40]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          10   4.99
2    Tuesday    Espresso          10   4.99
3    Tuesday       Latte          10   4.99
4  Wednesday    Espresso          35   4.99

In [41]:
coffee.reset_index(drop=True)

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          10   4.99
2     Tuesday    Espresso          10   4.99
3     Tuesday       Latte          10   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [42]:
import numpy as np

In [43]:
#Теперь добавим колонку с простым условием:
coffee['new_price'] = np.where(coffee['Coffee Type']=='Espresso', 3.99, 5.99)
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          10   4.99       5.99
2    Tuesday    Espresso          10   4.99       3.99
3    Tuesday       Latte          10   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

In [44]:
#удалим колонку:
coffee.drop(columns=['price'], inplace=True)

In [45]:
coffee.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       3.99
1     Monday       Latte          10       5.99
2    Tuesday    Espresso          10       3.99
3    Tuesday       Latte          10       5.99
4  Wednesday    Espresso          35       3.99

In [46]:
# важный момент - чтобы создать копию df - нужно использовать метод copy - иначе будет ссылка на оригинал и изменения будут в обоих df:
coffee_copy = coffee.copy()

In [47]:
coffee['revenue']= coffee['Units Sold'] * coffee['new_price']

In [48]:
coffee.head()

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          10       5.99    59.90
2    Tuesday    Espresso          10       3.99    39.90
3    Tuesday       Latte          10       5.99    59.90
4  Wednesday    Espresso          35       3.99   139.65

In [49]:
#переименуем колонку:
coffee.rename(columns={'new_price':'price'}, inplace=True)

In [50]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          10   5.99    59.90
2    Tuesday    Espresso          10   3.99    39.90
3    Tuesday       Latte          10   5.99    59.90
4  Wednesday    Espresso          35   3.99   139.65

In [51]:
bios_new = bios.copy()

In [52]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [53]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [54]:
#поработаем с объектами даты и времени
bios_new['born_date']= pd.to_datetime(bios_new['born_date'])

In [55]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  datetime64[us]
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
 10  first_name    145500 non-null  object
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(6)
memory usage: 18.2+ MB

In [56]:
bios_new['Year of Birth'] = bios_new['born_date'].dt.year

In [57]:
bios_new[['name', 'Year of Birth']].head()

                    name  Year of Birth
0  Jean-François Blanchy         1886.0
1         Arnaud Boetsch         1969.0
2           Jean Borotra         1898.0
3        Jacques Brugnon         1895.0
4           Albert Canet         1878.0

In [58]:
#простые функции с lyambda:
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x: 'Tall' if x > 190 else 'Average' if x > 170 else 'Short')

In [59]:
bios_new[['name', 'height_cm', 'height_category']].head(10)

                    name  height_cm height_category
0  Jean-François Blanchy        NaN           Short
1         Arnaud Boetsch      183.0         Average
2           Jean Borotra      183.0         Average
3        Jacques Brugnon      168.0           Short
4           Albert Canet        NaN           Short
5      Nicolas Chatelain      181.0         Average
6          Patrick Chila      180.0         Average
7           Henri Cochet        NaN           Short
8          Marcel Cousin        NaN           Short
9     Guy de la Chapelle        NaN           Short

In [60]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   athlete_id       145500 non-null  int64
 1   name             145500 non-null  str
 2   born_date        143693 non-null  datetime64[us]
 3   born_city        110908 non-null  str
 4   born_region      110908 non-null  str
 5   born_country     110908 non-null  str
 6   NOC              145499 non-null  str
 7   height_cm        106651 non-null  float64
 8   weight_kg        102070 non-null  float64
 9   died_date        33940 non-null   str
 10  first_name       145500 non-null  object
 11  Year of Birth    143693 non-null  float64
 12  height_category  145500 non-null  str
dtypes: datetime64[us](1), float64(3), int64(1), object(1), str(7)
memory usage: 21.3+ MB

In [61]:
def categorize_athlete(row):
    if pd.isna(row['height_cm']) or pd.isna(row['weight_kg']):
        return 'Unknown'    
    elif row['height_cm'] < 170 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] >= 170 and row['height_cm'] < 190 and row['weight_kg'] >= 70 and row['weight_kg'] < 80:
        return 'Middleweight'
    else:
        return 'Heavyweight'

In [62]:
bios_new['Category'] = bios_new.apply(categorize_athlete, axis=1)

In [63]:
bios_new[['name', 'height_cm',  'weight_kg', 'Category']].head()

                    name  height_cm  weight_kg      Category
0  Jean-François Blanchy        NaN        NaN       Unknown
1         Arnaud Boetsch      183.0       76.0  Middleweight
2           Jean Borotra      183.0       76.0  Middleweight
3        Jacques Brugnon      168.0       64.0   Lightweight
4           Albert Canet        NaN        NaN       Unknown

### Merging and Concatinating

In [64]:
nocs = pd.read_csv('../complete-pandas-tutorial/data/noc_regions.csv')

In [65]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [66]:
bios2 = pd.merge(bios_new, nocs, left_on='born_country', right_on='NOC', how='left')

In [67]:
bios2.rename(columns={'region':'born_country_full'}, inplace=True)

In [68]:
bios2[['name', 'born_country', 'born_country_full']].head(15)

                       name born_country born_country_full
0     Jean-François Blanchy          FRA            France
1            Arnaud Boetsch          FRA            France
2              Jean Borotra          FRA            France
3           Jacques Brugnon          FRA            France
4              Albert Canet          GBR                UK
5         Nicolas Chatelain          FRA            France
6             Patrick Chila          FRA            France
7              Henri Cochet          FRA            France
8             Marcel Cousin          FRA            France
9        Guy de la Chapelle          FRA            France
10  Élie, Comte de Lastours          FRA            France
11              Max Decugis          FRA            France
12                J. Defert          NaN               NaN
13           Étienne Durand          NaN               NaN
14              Damien Éloi          FRA            France

In [69]:
results.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  str
 2   discipline  308407 non-null  str
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  str
 7   team        121714 non-null  str
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   str
dtypes: bool(1), float64(2), int64(1), str(7)
memory usage: 46.0 MB

In [70]:
combined_df = pd.merge(results, bios, on='athlete_id', how='left')

In [71]:
# Разрешить отображение всех столбцов
pd.set_option('display.max_columns', None)

# Опционально: предотвратить перенос столбцов на новую строку
pd.set_option('display.width', None)

In [72]:
combined_df.head(10)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
5,1996.0,Summer,Tennis,"Singles, Men (Olympic)",Arnaud Boetsch,2,FRA,NaN,17.0,True,NaN,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
6,1996.0,Summer,Tennis,"Doubles, Men (Olympic)",Arnaud Boetsch,2,FRA,Guillaume Raoux,17.0,True,NaN,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
7,1924.0,Summer,Tennis,"Singles, Men (Olympic)",Jean Borotra,3,FRA,NaN,4.0,False,NaN,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
8,1924.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean Borotra,3,FRA,Marguerite Billout,15.0,True,NaN,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
9,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean Borotra,3,FRA,René Lacoste,3.0,False,Bronze,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17

### Работа с Null

In [73]:
import numpy as np

In [74]:
#coffee = pd.read_csv('../complete-pandas-tutorial/warmup-data/coffee.csv')
#coffee

In [75]:
coffee.loc[[0,1], 'Units Sold'] = np.nan

In [76]:
#как видим теперь часть данных у нас null:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   12 non-null     float64
 3   price        14 non-null     float64
 4   revenue      14 non-null     float64
dtypes: float64(3), str(2)
memory usage: 883.0 bytes

In [77]:
#чтобы посчитать количество null:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
price          0
revenue        0
dtype: int64

In [78]:
# что можем сделать:
coffee.fillna(30) # хардом заполнить каким-нибудь значением

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        30.0   3.99    99.75
1      Monday       Latte        30.0   5.99    59.90
2     Tuesday    Espresso        10.0   3.99    39.90
3     Tuesday       Latte        10.0   5.99    59.90
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [79]:
# более разумным решением будет:
coffee.fillna(coffee['Units Sold'].mean())

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        32.5   3.99    99.75
1      Monday       Latte        32.5   5.99    59.90
2     Tuesday    Espresso        10.0   3.99    39.90
3     Tuesday       Latte        10.0   5.99    59.90
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [80]:
# еще более мудрое решение - интерполировать. Для этого нужно переставить данные местами
n = len(coffee)

In [81]:
idx = np.concatenate([
    [2, 3],              # Кого двигаем
    np.arange(0, 2),     # Кто был в начале
    np.arange(4, n)      # Все остальные
])

In [82]:
coffee = coffee.iloc[idx].reset_index(drop=True)

In [83]:
coffee['Units Sold'].interpolate()

0     10.000000
1     10.000000
2     18.333333
3     26.666667
4     35.000000
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [84]:
# можно дропнить часть na (смотрим только на subset)
coffee.dropna(subset='Units Sold')

          Day Coffee Type  Units Sold  price  revenue
0     Tuesday    Espresso        10.0   3.99    39.90
1     Tuesday       Latte        10.0   5.99    59.90
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [85]:
# можем отобрать только значения na в конкретном столбце:
coffee[coffee['Units Sold'].isna()] # либо notna()

      Day Coffee Type  Units Sold  price  revenue
2  Monday    Espresso         NaN   3.99    99.75
3  Monday       Latte         NaN   5.99    59.90

In [86]:
#отобрать nan во всех столбцах:
rows_with_nan = coffee[coffee.isna().any(axis=1)]
rows_with_nan

      Day Coffee Type  Units Sold  price  revenue
2  Monday    Espresso         NaN   3.99    99.75
3  Monday       Latte         NaN   5.99    59.90

In [87]:
#coffee['Units Sold'].to_clipboard(index=False, excel=True, decimal=",")

### Агрегация данных

In [88]:
bios.head(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [89]:
#Подсчитаем сколько атлетов было из каких городов
bios.value_counts('born_city')

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [90]:
#специфицированный запрос:
bios[bios['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Tennessee                 62
Kentucky                  62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [91]:
# сгруппируем:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    36.666667
Latte       28.333333
Name: Units Sold, dtype: float64

In [97]:
# аналог простой сводной таблицы:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price':'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday           45.0   3.99
            Monday            0.0   3.99
            Saturday         45.0   3.99
            Sunday           45.0   3.99
            Thursday         40.0   3.99
            Tuesday          10.0   3.99
            Wednesday        35.0   3.99
Latte       Friday           35.0   5.99
            Monday            0.0   5.99
            Saturday         35.0   5.99
            Sunday           35.0   5.99
            Thursday         30.0   5.99
            Tuesday          10.0   5.99
            Wednesday        25.0   5.99

In [105]:
# 1. Создаем список с правильным порядком
days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

In [108]:
# pivots:
pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue')
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   59.90
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday         39.90   59.90
Wednesday      139.65  149.75

In [103]:
#можно фильтровать pivot:
pivot.loc['Monday', 'Latte']

np.float64(59.900000000000006)

In [110]:
# 2. Переопределяем индекс как категориальный с заданным порядком
pivot.index = pd.CategoricalIndex(pivot.index, categories=days_order, ordered=True)

# 3. Сортируем по этому индексу
pivot = pivot.sort_index()
pivot

Coffee Type  Espresso   Latte
Day
Monday          99.75   59.90
Tuesday         39.90   59.90
Wednesday      139.65  149.75
Thursday       159.60  179.70
Friday         179.55  209.65
Saturday       179.55  209.65
Sunday         179.55  209.65

In [114]:
pivot.sum() # тоталы по колонкам
pivot.sum(axis=0)

Coffee Type
Espresso     977.55
Latte       1078.20
dtype: float64

In [115]:
pivot.sum(axis=1) #тоталы по строкам

Day
Monday       159.65
Tuesday       99.80
Wednesday    289.40
Thursday     339.30
Friday       389.20
Saturday     389.20
Sunday       389.20
dtype: float64